### ISSUE TITLE
Generating images with SD-1.5

### ISSUE THREAD

**Issue by Reagan1311** [EPJ-coding/ReCorD#1]
Hi, thank you for the excellent work. I noticed that the code uses StableDiffusion XL as the default backbone, which consumes a significant amount of memory. I wonder if the code supports inference with a lighter model like SD-1.5. If so, could you please guide me on how to modify the code accordingly? Thanks!

**Comment by j1anglin** [comment]
You're welcome! We will update the code to support SD-1.5 in the coming days. Thanks for your patience!

**Comment by j1anglin** [comment]
Hi, we have updated support for the SD model.
